// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfO2ocSNhoL5jQEtdYHGIgHKtqmQMBEtA',
    appId: '1:193707534280:web:9460ecab331421c42bc2fd',
    messagingSenderId: '193707534280',
    projectId: 'medicall-742c7',
    authDomain: 'medicall-742c7.firebaseapp.com',
    storageBucket: 'medicall-742c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1P117DNQE5n9a9FS7CwEKV2emPQ4kfIo',
    appId: '1:193707534280:android:8f5a12fe9971f3312bc2fd',
    messagingSenderId: '193707534280',
    projectId: 'medicall-742c7',
    storageBucket: 'medicall-742c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfki6MCnxRvp9Jrls_TmbRLQbDzdb0pU',
    appId: '1:193707534280:ios:9e29f84d81b76cfd2bc2fd',
    messagingSenderId: '193707534280',
    projectId: 'medicall-742c7',
    storageBucket: 'medicall-742c7.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWfki6MCnxRvp9Jrls_TmbRLQbDzdb0pU',
    appId: '1:193707534280:ios:9e29f84d81b76cfd2bc2fd',
    messagingSenderId: '193707534280',
    projectId: 'medicall-742c7',
    storageBucket: 'medicall-742c7.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfO2ocSNhoL5jQEtdYHGIgHKtqmQMBEtA',
    appId: '1:193707534280:web:de6f52a4f812bd932bc2fd',
    messagingSenderId: '193707534280',
    projectId: 'medicall-742c7',
    authDomain: 'medicall-742c7.firebaseapp.com',
    storageBucket: 'medicall-742c7.firebasestorage.app',
  );
}
